posts/urls.py
from django.conf.urls import url
from . import views


app_name = 'posts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.create, name='create'),
    url(r'^(?P<post_id>\d+)/$', views.detail, name="detail"),
    url(r'^(?P<post_id>\d+)/update/$', views.update, name='update'),
    url(r'^(?P<post_id>\d+)/delete/$', views.delete, name='delete'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', views.login, name='login'),


]

trydjango19/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('posts.urls')),

]

# https://github.com/codingforentrepreneurs/Guides/blob/master/all/common_url_regex.md

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse


# Create your models here.
def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    content = models.TextField(max_length=5000)
    image = models.ImageField(null=True, blank=True, upload_to=upload_location,
                              height_field="height_field", width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    draft = models.BooleanField(default=False)
    publish = models.DateTimeField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={"post_id": self.id})
        # return "/posts/%s/" % self.id

    # this help to retrieve objects in the reverse order - represents reverse
    class Meta:
        ordering = ["-timestamp", "-updated"]

posts/forms.py
from django import forms
from django.contrib.auth.models import User


from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish'
        ]


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password'
        ]


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']

posts/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views.generic.edit import View
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.contrib import messages
from django.utils import timezone

from .models import Post
from .forms import PostForm, UserForm, LoginForm


# Create your views here.
def hello(request):
    return HttpResponse('Hello World!!')


def login(request):
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return reverse('posts:index')
            else:
                return render(request, 'posts/login.html', {'form': form})
        else:
            return render(request, 'posts/login.html', {'form': form})
    return render(request, 'posts/login.html', {'form': form})


def index(request):
    # logout(request)
    # query_set_list = Post.objects.all().order_by('-timestamp')
    query_set_list = Post.objects.filter(publish__lte=timezone.now()).order_by('-timestamp')
    query = request.GET.get('q')
    if query:
        query_set_list = query_set_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(author__first_name__icontains=query)).distinct()

    paginator = Paginator(query_set_list, 5)  # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        query_set = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        query_set = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        query_set = paginator.page(paginator.num_pages)
    context = {
        'object_list': query_set,
        'title': 'Post List'
    }
    return render(request, 'posts/index.html', context)


def detail(request, post_id=None):
    data = get_object_or_404(Post, id=post_id)
    context = {
        'title': data.title,
        'instance': data
    }
    return render(request, 'posts/detail.html', context)


def create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    # to save the data in the db
    if form.is_valid():
        data = form.save(commit=False)
        data.author = request.user
        data.save()
        messages.success(request, 'Successfully created!!')
        return HttpResponseRedirect(data.get_absolute_url())
    if form.errors:
        messages.error(request, 'Not created!!')

    context = {
        'form': form
    }
    return render(request, 'posts/post_form.html', context)
    # if request.method == 'POST':
    #     print request.POST.get('content')


def update(request, post_id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, 'Successfully Updated!!')
        # success message
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'title': instance.title,
        'instance': instance,
        'form': form
        }
    return render(request, 'posts/post_form.html', context)


def delete(request, post_id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, id=post_id)
    instance.delete()
    messages.success(request, 'Successfully Deleted')
    return redirect('posts:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'posts/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data..
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            # cleaned normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return user object if credentials are correct
            user = authenticate(username= username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('posts:index')
        return render(request, self.template_name, {'form': form})

posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_block %}Django Blog Application {% endblock %}</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

</head>
<body>
<div class="container">
    {% block content %}

    {% endblock content %}
</div>
{% include 'posts/messages.html' %}


<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


</body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7&appId=1619911288324356";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

</html>

posts/templates/posts/detail.html
{% extends 'posts/base.html' %}

{% block content %}

    <div class="col-sm-8 col-sm-offset-2">
    <img src="{{ instance.image.url }}" class="img-responsive">
    <h1>{{ title }} <small>{% if instance.draft %}
    <span style="color: #993300"> Draft</span>
    {% endif %} {{ instance.publish }}</small></h1>
    <div class="fb-like" data-href="{{ request.build_absolute_url }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>
     </hr></br>
    <p>
        {{ instance.content }}
        {% if instance.author %}
            </p>
    <p>Author: {{ instance.author.get_full_name }}</p>
    {% endif %}

    <div class="row">
    </hr>   </br>
    <div class="fb-comments" data-href= "{{ request.build_absolute_url }}" data-numposts="5"></div>
    </div>
    </div>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'posts/base.html' %}

{% block content %}
<div class="col-sm-8 col-sm-offset-2">
<a href="{% url 'posts:index' %}">
<h1>Posts List</h1>
</a>
<form method="get" action="">
    <input type="text" name="q"  placeholder="Search query" value="{{ request.GET.q}}"/>
    <input type="submit"  value="Search"/>
</form>

    {% for obj in object_list %}
<div class="row">
     <div class="col-sm-12">
    <div class="thumbnail">
        {% if obj.image %}
        <img src="{{ obj.image.url }}" class="img-responsive">
        {% endif %}

      <div class="caption">
        <h3><a href="{{ obj.get_absolute_url }}"> {{ obj.title }} </a>
        <small>{{ obj.timestamp |timesince }} ago</small>
        </h3>
          {% if obj.author %}
    <p>Author: {{ obj.author.get_full_name }}</p>
    {% endif %}
        <p>{{ obj.content |linebreaks|truncatechars:120 }}</p>
          <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">View</a>
      </div>
    </div>
  </div>
</div>
    {% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page={{ object_list.previous_page_number }}{% if request.GET.q %}
            &q={{ request.GET.q }}
            {% endif %} ">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}{% if request.GET.q %}
            &q={{ request.GET.q }}
            {% endif %} ">next</a>
        {% endif %}
    </span>
</div>
</div>

{% endblock content %}

posts/templates/posts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>

<h2> Login </h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit"/>
</form>
<a href="{% url 'posts:register' %}">Don't have account??</a>

</body>
</html>

posts/templates/posts/messages.html
    {% if messages %}
        <ul class="messages">
         {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
         {% endfor %}
        </ul>
{% endif %}

posts/templates/posts/post_form.html
{% extends 'posts/base.html' %}

{% block content %}
<div class="col-sm-8 col-sm-offset-2">
    <h1> Form </h1>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create Post"/>
    </form>
</div>

{% endblock content %}

posts/templates/posts/registration_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<h2>Create User </h2>
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
</form>

</body>
</html>